apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: hello-api-template

spec:
  scenario: hello-api

  inputs: {}

  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "2"

    spec:
      containers:
        - name: hello-api
          image: ghcr.io/tdc-e-moriya/hello-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"