apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate

metadata:
  name: hello-api-template
  labels:
    ai.sap.com/resource-group: default

spec:
  scenario: hello-api

  template:
    spec:
      containers:
      - name: hello-api
        image: ghcr.io/tdc-e-moriya/hello-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000